# Generated by Django 4.2.6 on 2023-10-13 13:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_dept',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(default=datetime.datetime(2023, 10, 13, 13, 55, 43, 154727, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
