# Generated by Django 4.2.6 on 2023-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors_created_at_doctors_doc_dept_doctors_doc_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_img',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
