# Generated by Django 4.2.6 on 2023-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_doc_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_icon', models.CharField(default='nil', max_length=100)),
                ('dept_desc', models.TextField()),
            ],
        ),
    ]
