# Generated by Django 4.2.6 on 2023-10-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='departments',
        ),
    ]
