# Generated by Django 4.2.6 on 2023-10-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_department_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='dept_icon',
        ),
    ]
