# Generated by Django 4.2.6 on 2023-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_departments_dept_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dept_icon',
            field=models.CharField(default='nil', max_length=100),
        ),
    ]
