# Generated by Django 4.2.6 on 2023-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_departments_dept_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_icon',
            field=models.CharField(default='fas fa-heart', max_length=100),
        ),
    ]
