# Generated by Django 4.2.6 on 2023-10-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_departments_dept_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='dept_icon',
        ),
    ]
