# Generated by Django 4.2.6 on 2023-10-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_departments_dept_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
    ]
