# Generated by Django 4.2.6 on 2023-10-14 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='p_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
