# Generated by Django 4.2.6 on 2023-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_appointments_p_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='p_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='p_name',
            field=models.CharField(max_length=1000),
        ),
    ]
